### ISSUE TITLE
Re Review needed

### ISSUE THREAD

**Issue by sohamjaiswal** [tunlrs/mono#11]
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/f0f3a915-bc1c-4ea0-b180-f961f0ea45c8">
https://doc.rust-lang.org/std/pin/index.html

according to that... 
https://github.com/tunlrs/mono/blob/e297daf3e0479e7dafe78b77621bbc290f922510/client/src-tauri/src/lib.rs#L10

<img width="978" alt="image" src="https://github.com/user-attachments/assets/58df46ea-3bc9-4c21-b0af-d4878ad75d90">
this does not seem right, it works but, i mean, the object aint gonna stay for the whole runtime of the application, and idk how long returned value stays pinned for, i would appreciate if someone could confirm if this is the correct approach for this

**Comment by Serpent03** [comment]
Your approach might be the safest one, atleast according to this article:

https://os.phil-opp.com/async-await/#the-problem-with-self-referential-structs

According to this, in addition to checking futures() for an actual object, Pin does not allow it to move inside the memory as long as you reference it, so if this object is needed outside the function, I think it should be okay to use it

Not very sure on this one, I'll keep looking

**Comment by sohamjaiswal** [comment]
closing after a careful read of 

https://doc.rust-lang.org/std/pin/index.html
